services:
  postgres:
    image: postgres:16-alpine
    container_name: clinic-db
    restart: always
    environment:
      POSTGRES_USER: ${DB_USERNAME:-postgres}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-postgres}
      POSTGRES_DB: ${DB_NAME:-clinic_db}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  ms-appointment:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ms-appointment
    ports:
      - "8080:8080"
    depends_on:
      - postgres # Asegura que la BD intente levantar antes que la app
    environment:
      SPRING_PROFILES_ACTIVE: local
      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: ${DB_NAME:-clinic_db}
      DB_USERNAME: ${DB_USERNAME:-postgres}
      DB_PASSWORD: ${DB_PASSWORD:-postgres}

volumes:
  postgres_data: