# ---------- Build stage ----------

FROM maven:3.9.9-eclipse-temurin-21 AS build

WORKDIR /workspace

# Copy Maven files first (better Docker cache)

COPY pom.xml .

COPY .mvn .mvn

COPY mvnw .

# Download dependencies

RUN ./mvnw dependency:go-offline

# Copy application source

COPY src src

# Build executable Spring Boot JAR

RUN ./mvnw clean package -DskipTests

# ---------- Runtime stage ----------

FROM eclipse-temurin:21-jre-alpine

WORKDIR /app

# Copy the executable JAR generated by Spring Boot

COPY --from=build /workspace/target/ms-appointment.jar app.jar

EXPOSE 8080

ENTRYPOINT ["java","-jar","/app/app.jar"]